[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "optimization_project"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.4",
    "scipy>=1.17.1",
    "matplotlib>=3.10.9", 
    "seaborn>=0.13.2"
]

[tool.setuptools.packages.find]
include = ["optimization_project*"]